### ISSUE TITLE
QA realignment

### ISSUE THREAD

**Issue by boomditty** [boomditty/ecosystem-operations-review-excellence#11]
- More in line with T1 Review, T2 Review, T2 Excellence schedules
- TaskUs QA will now directly report to the ART OM (Charlene G.)
- Alleviate tasks from QA Specialist that were added as a result of the removal of MaestroQA tool
- Ticket generation
- QA rubric reporting per Specialist
- All other reports (if necessary) [found here](https://docs.google.com/spreadsheets/d/1xgx8hZ3D3xZa4e9_HuGFjOzT8rskEScq-K333BCqAkY/edit?usp=sharing)

**Comment by CKNis** [comment]
TLs accessing and approving QA scores before specialists (alleviate some need to dispute as TLs)

**Comment by boomditty** [comment]
[New draft](https://docs.google.com/document/d/1InZQEBAoGmlpqrH6BNsTZe-L-j5iXmk7xPmH5crXec8/edit?usp=sharing)
