### ISSUE TITLE
New productivity metrics & benchmark

### ISSUE THREAD

**Issue by boomditty** [boomditty/ecosystem-operations-review-excellence#16]
Our current metric of 3 apps per day for TaskUs is outdated and arbitrary. 
Goal here is to centre their productivity around minimizing TTP (Time to publish). 
Come up with a new way for TLs to base the productivity of their teams and what to report on during MQRs.

**Comment by CKNis** [comment]
+ App excellence metrics. Audit topics should be considered when assessing productivity. Not all audit topics are equal in terms of complexity and time.
